spring:
  redis:
    host: 127.0.0.1  #地址
    password: 123456 #密码
    port: 6379 #端口号
    lettuce:
      pool:
        max-active: 100 #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 100 #连接池中的最大空闲连接
        min-idle: 0    #连接池中的最小空闲连接
    # 连接超时时间（毫秒）    
    timeout: 30000 #

  servlet: 
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
#oss
web: 
   file: #forum-userimage.oss-cn-beijing.aliyuncs.com
   #不同的服务器，地址不同 http://
      endpoint: oss-cn-beijing.aliyuncs.com 
      #去OSS控制台获取
      keyid: LTAI4FcZ2KgJPswhYdJ8mKPd 
      #去OSS控制台获取
      keysecret: I74ek6jtQbYATb0YkAuWbHhkhOx9Mw 
      #这个自己创建bucket时的命名，控制台创建也行，代码创建也行
      bucketname: forum-userimage 
      #文件路径，我这里是blog
      filehost: articleImages